### ISSUE TITLE
Uppgradera errorhandling i irc.py

### ISSUE THREAD

**Issue by nycz** [memery/memery-legacy#100]
Låt run() bli en wrapper runt vad som nu är run så att istället för
`memery.py -> irc.py -> run()`
det blir
`memery.py -> irc.py -> run() -> oldrun()` 
där oldrun() är det som nu är run() och nya run() enbart finns till för att fånga runtimeerrors som tex alla subklasser av ConnectionError (BrokenPipeError, ConnectionResetError etc)

**Comment by nycz** [comment]
Lite rådata:

```
Traceback (most recent call last):
  File "memery.py", line 27, in <module>
    main()
  File "memery.py", line 12, in main
    result = irc.run(message, settings, startuptime)
  File "/home/nycz/gitrepos/memery-new/irc.py", line 283, in run
    send(irc, 'PING :arst')
  File "/home/nycz/gitrepos/memery-new/irc.py", line 57, in send
    irc.send(bytes(text + '\n', 'utf-8'))
  File "/usr/lib/python3.3/ssl.py", line 386, in send
    v = self._sslobj.write(data)
BrokenPipeError: [Errno 32] Broken pipe
```

och

```
Traceback (most recent call last):
  File "memery.py", line 27, in <module>
    main()
  File "memery.py", line 12, in main
    result = irc.run(message, settings, startuptime)
  File "/home/nycz/gitrepos/memery-new/irc.py", line 321, in run
    readdata = irc.read(4096)
  File "/usr/lib/python3.3/ssl.py", line 329, in read
    v = self._sslobj.read(len or 1024)
ConnectionResetError: [Errno 104] Connection reset by peer
```

Notera att borken pipe sker i send() medan reset sker i read(). Jobbigt att skriva flera catchsatser -> enklare att wrappa skiten och fånga allt en nivå högre upp. Let it crawwwwsh baby

**Comment by kqr** [comment]
förhoppningsvis fixat, men det är svårt att framkalla broken pipe. :c
