### ISSUE TITLE
Fånga BrokenPipeError

### ISSUE THREAD

**Issue by nycz** [memery/memery-legacy#99]
<pre>Traceback (most recent call last):
  File "memery.py", line 27, in <module>
    main()
  File "memery.py", line 12, in main
    result = irc.run(message, settings, startuptime)
  File "/home/nycz/gitrepos/memery-new/irc.py", line 283, in run
    send(irc, 'PING :arst')
  File "/home/nycz/gitrepos/memery-new/irc.py", line 57, in send
    irc.send(bytes(text + '\n', 'utf-8'))
  File "/usr/lib/python3.3/ssl.py", line 386, in send
    v = self._sslobj.write(data)
BrokenPipeError: [Errno 32] Broken pipe</pre>

**Comment by nycz** [comment]
Wontfix, se istället #100
